[package]
name = "serverbee-deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
zip = "0.6.2"
daemonize = "0.4.1"