name: Release

permissions:
    contents: write

on:
    push:
        tags:
            - v[0-9]+.*

jobs:
#  build:
#    name: release ${{ matrix.target }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        target:
#          [
#            x86_64-pc-windows-gnu,
#            x86_64-unknown-linux-musl
#          ]
#        package: [web, deploy]
#    steps:
#      - uses: actions/checkout@master
#      - name: Compile and release
#        id: compile
#        uses: rust-build/rust-build.action@v1.3.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RUSTTARGET: ${{ matrix.target }}
#          SRC_DIR: ${{ matrix.package }}
#          ARCHIVE_NAME: serverbee-${{ matrix.package }}-${{ matrix.target }}
#          UPLOAD_MODE: none
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: serverbee-${{ matrix.target }}
#          path: |
#            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
#            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  build:
    strategy:
      fail-fast: false
      matrix:
        package: [ web, deploy ]
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            suffix: .exe
            target: x86_64-pc-windows-gnu
          - host: windows-latest
            suffix: .exe
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            suffix: .exe
            target: aarch64-pc-windows-msvc
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-musl
          - host: ubuntu-latest
            name: -ubuntu22
            target: x86_64-unknown-linux-musl
          - host: ubuntu-latest
            name: -ubuntu22
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            name: -ubuntu22
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            name: -ubuntu22
            target: aarch64-unknown-linux-musl
    name: build serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.settings.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ./target/release
          path: serverbee-${{ matrix.package }}${{ matrix.settings.suffix }}
          filename: serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}.zip
#      - name: Display structure of Upload files
#        run: ls -R
#      - name: Zip artifact
#        run: zip -j serverbee-${{ matrix.package }}-${{ matrix.target }} ./target/release/serverbee-${{ matrix.package }}
      - uses: randomairborne/r2-release@main
        with:
          endpoint: ${{ secrets.S3_ENDPOINT }}
          accesskeyid: ${{ secrets.S3_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: serverbee
          file: ./target/release/serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}.zip
          destination: /cli/${{ github.ref_name }}/serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}${{ matrix.settings.suffix }}
          path: ./target/release/serverbee-${{ matrix.package }}${{ matrix.settings.name }}-${{ matrix.settings.target }}.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
#      - name: Display structure of downloaded files
#        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'serverbee-*/*.zip'
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
