name: Release

permissions:
    contents: write

on:
    push:
        tags:
            - v[0-9]+.*
        branches:
            - ci/1.1.1/cross-compile

jobs:
#  build:
#    name: release ${{ matrix.target }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        target:
#          [
#            x86_64-pc-windows-gnu,
#            x86_64-unknown-linux-musl
#          ]
#        package: [web, deploy]
#    steps:
#      - uses: actions/checkout@master
#      - name: Compile and release
#        id: compile
#        uses: rust-build/rust-build.action@v1.3.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RUSTTARGET: ${{ matrix.target }}
#          SRC_DIR: ${{ matrix.package }}
#          ARCHIVE_NAME: serverbee-${{ matrix.package }}-${{ matrix.target }}
#          UPLOAD_MODE: none
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: serverbee-${{ matrix.target }}
#          path: |
#            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
#            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  build-macos:
    name: release macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        package: [web, deploy]
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ./target/release
          path: serverbee-${{ matrix.package }}
          filename: serverbee-${{ matrix.package }}-${{ matrix.target }}.zip
      - name: Display structure of downloaded files
        run: ls -R
#      - name: Zip artifact
#        run: zip -j serverbee-${{ matrix.package }}-${{ matrix.target }} ./target/release/serverbee-${{ matrix.package }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverbee-${{ matrix.package }}-${{ matrix.target }}
          path: ./target/release/serverbee-${{ matrix.package }}-${{ matrix.target }}.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
#      - build
      - build-macos
    steps:
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'serverbee-*/*.zip'
          tag: v1.1.1
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
